#!/usr/bin/env python3
"""Regenerate artificial protocol fixtures using independently generated Python schemas.
No network, package installation, radio access, or application decoder is used.
Run separately for each version to isolate the protobuf descriptor pool.
"""
import argparse
import json
import os
from pathlib import Path
import sys

parser = argparse.ArgumentParser()
parser.add_argument('--schema-dir', required=True, type=Path)
parser.add_argument('--protobuf-dir', required=True, type=Path)
parser.add_argument('--version', required=True, choices=['2.7.19', '2.8.0'])
parser.add_argument('--output', required=True, type=Path)
args = parser.parse_args()
sys.dont_write_bytecode = True
os.environ['PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION'] = 'python'
sys.path[:0] = [str(args.protobuf_dir.resolve()), str(args.schema_dir.resolve())]
from meshtastic import mesh_pb2 as mesh, telemetry_pb2 as telemetry

fixtures = []
def add(name, port, payload, kind, request_id=0, signature=False, want_response=False):
    data = mesh.Data(portnum=port, request_id=request_id, want_response=want_response)
    if payload is not None:
        data.payload = payload if isinstance(payload, bytes) else payload.SerializeToString(deterministic=True)
    if signature:
        data.xeddsa_signature = bytes(range(64))
    fixtures.append((f'{args.version}:{name}', data.SerializeToString(deterministic=True).hex(), kind, port, request_id, signature))

add('empty-traceroute', 70, mesh.RouteDiscovery(), 'traceroute', want_response=True)
add('traceroute-reply', 70, mesh.RouteDiscovery(route=[0x11223344, 0xffffffff], snr_towards=[-31, 24], route_back=[0x55667788], snr_back=[-128]), 'traceroute', 0x12345678)
add('routing-none', 5, mesh.Routing(error_reason=0), 'routing')
add('routing-request', 5, mesh.Routing(route_request=mesh.RouteDiscovery()), 'routing')
add('routing-reply', 5, mesh.Routing(route_reply=mesh.RouteDiscovery(route_back=[0x55667788], snr_back=[-12])), 'routing', 0x12345678)
add('text', 1, b'Independent official-schema fixture', 'text')
add('node', 4, mesh.User(id='!11223344', long_name='Artificial fixture', short_name='TEST', hw_model=43, role=2), 'node')
add('position', 3, mesh.Position(latitude_i=-450000000, longitude_i=900000000, altitude=-10, time=1700000000), 'position')
add('telemetry', 67, telemetry.Telemetry(time=1700000001, device_metrics=telemetry.DeviceMetrics(battery_level=80, voltage=3.7, channel_utilization=2.5)), 'device telemetry')
add('unsupported', 256, b'Artificial unsupported payload', '')
if args.version == '2.8.0':
    add('signature-shape', 1, b'Artificial signature presence only', 'text', signature=True)

lines = ['// Artificial fixtures; generated by tools/generate_protocol_fixtures.py.', '// Official schema '+args.version+'; protoc 36.1 / Python protobuf 7.36.1.']
for name, encoded, kind, port, request_id, signature in fixtures:
    lines.append('{' + ', '.join([json.dumps(name), json.dumps(encoded), json.dumps(kind), str(port), str(request_id)+'u', str(signature).lower()]) + '},')
args.output.write_text('\n'.join(lines)+'\n', encoding='utf-8')
print(f'{args.version}: wrote {len(fixtures)} artificial fixtures')
