# SPDX-License-Identifier: GPL-3.0-or-later
include_guard(GLOBAL)
option(OVMESH_ENABLE_RAK5146 "Build experimental receive-only RAK5146 USB worker" ON)
set(OVMESH_HAVE_RAK5146_WORKER FALSE)
if(NOT OVMESH_ENABLE_RAK5146)
  message(STATUS "RAK5146 USB worker disabled by OVMESH_ENABLE_RAK5146=OFF.")
  return()
endif()
if(NOT UNIX OR WIN32)
  message(STATUS "RAK5146 USB worker unavailable: this implementation requires macOS or Linux.")
  return()
endif()
if(NOT APPLE)
  if(NOT CMAKE_SYSTEM_NAME STREQUAL "Linux")
    message(STATUS "RAK5146 worker is supported on macOS/Linux only; other receivers remain available.")
    return()
  endif()
  include(CheckSymbolExists)
  set(CMAKE_REQUIRED_DEFINITIONS -D_GNU_SOURCE=1)
  check_symbol_exists(posix_spawn_file_actions_addclosefrom_np "spawn.h" OVMESH_RAK_CLOSEFROM_AVAILABLE)
  unset(CMAKE_REQUIRED_DEFINITIONS)
  if(NOT OVMESH_RAK_CLOSEFROM_AVAILABLE)
    message(STATUS "RAK5146 worker disabled: libc lacks safe child descriptor isolation (glibc 2.34+ provides it). Other receivers remain available.")
    return()
  endif()
endif()
get_filename_component(_rak_root "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(_rak_hal "${_rak_root}/third_party/sx1302_hal")
set(_rak_sources
  loragw_ad5338r.c loragw_aux.c loragw_cal.c loragw_com.c loragw_debug.c
  loragw_hal.c loragw_lbt.c loragw_mcu.c loragw_reg.c loragw_stts751.c
  loragw_sx1250.c loragw_sx125x.c loragw_sx1261.c loragw_sx1302.c
  loragw_sx1302_rx.c loragw_sx1302_timestamp.c loragw_usb.c
  sx1250_com.c sx1250_usb.c sx125x_com.c sx1261_com.c sx1261_usb.c)
list(TRANSFORM _rak_sources PREPEND "${_rak_hal}/libloragw/src/")
add_library(ovmesh_rak_hal STATIC ${_rak_sources}
  "${_rak_hal}/compat/no_external_bus.c" "${_rak_hal}/libtools/src/tinymt32.c")
target_include_directories(ovmesh_rak_hal PUBLIC "${_rak_hal}/libloragw/inc"
  PRIVATE "${_rak_hal}/libtools/inc")
set_target_properties(ovmesh_rak_hal PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED YES C_EXTENSIONS YES)
target_compile_definitions(ovmesh_rak_hal PRIVATE _GNU_SOURCE=1 _DARWIN_C_SOURCE=1)
target_compile_options(ovmesh_rak_hal PRIVATE "-include" "${_rak_hal}/compat/quiet_log.h")
if(NOT APPLE)
  target_link_libraries(ovmesh_rak_hal PRIVATE m)
endif()
add_executable(ovmesh-rak-worker "${_rak_root}/src/rak_worker.c")
target_link_libraries(ovmesh-rak-worker PRIVATE ovmesh_rak_hal)
target_compile_definitions(ovmesh-rak-worker PRIVATE _GNU_SOURCE=1 _DARWIN_C_SOURCE=1)
set_target_properties(ovmesh-rak-worker PROPERTIES C_STANDARD 11 C_STANDARD_REQUIRED YES C_EXTENSIONS YES)
if(OVMESH_SANITIZERS)
  target_compile_options(ovmesh_rak_hal PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
  target_compile_options(ovmesh-rak-worker PRIVATE -fsanitize=address,undefined -fno-omit-frame-pointer)
  target_link_options(ovmesh-rak-worker PRIVATE -fsanitize=address,undefined)
endif()
set(OVMESH_HAVE_RAK5146_WORKER TRUE)
# Parent CMake owns application dependency ordering, bundling/install, and macro.
